twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals: 
        notification: '@App\Services\Notification'
        cats: '@App\Twig\CatsExtension'
when@test:
    twig:
        strict_variables: true
